package com.lundih.usercontact.enums;

/**
 * This class standardises countries
 * <p>
 * The class ensures that a country provided from the user input is one of the expected values.
 * This reduces the chances that a typo will appear in the country (or even a non-existent one). It will also
 * allow the backend to restrict some countries from being provided in case such a situation ever arises
 *
 * @author lundih
 * @since 0.0.1
 */
public enum Country {
        AFGHANISTAN("Afghanistan"),
        ALBANIA("Albania"),
        ALGERIA("Algeria"),
        ANDORRA("Andorra"),
        ANGOLA("Angola"),
        ANTIGUA_AND_DEPS("Antigua & Deps"),
        ARGENTINA("Argentina"),
        ARMENIA("Armenia"),
        ARUBA("Aruba"),
        AUSTRALIA("Australia"),
        AUSTRIA("Austria"),
        AZERBAIJAN("Azerbaijan"),
        BAHAMAS("Bahamas"),
        BAHRAIN("Bahrain"),
        BANGLADESH("Bangladesh"),
        BARBADOS("Barbados"),
        BELARUS("Belarus"),
        BELGIUM("Belgium"),
        BELIZE("Belize"),
        BENIN("Benin"),
        BHUTAN("Bhutan"),
        BOLIVIA("Bolivia"),
        BOSNIA_HERZEGOVINA("Bosnia Herzegovina"),
        BOTSWANA("Botswana"),
        BRAZIL("Brazil"),
        BRUNEI("Brunei"),
        BULGARIA("Bulgaria"),
        BURKINA("Burkina"),
        BURUNDI("Burundi"),
        CAMBODIA("Cambodia"),
        CAMEROON("Cameroon"),
        CANADA("Canada"),
        CAPE_VERDE("Cape Verde"),
        CENTRAL_AFRICAN_REP("Central African Rep"),
        CHAD("Chad"),
        CHILE("Chile"),
        CHINA("China"),
        COLOMBIA("Colombia"),
        COMOROS("Comoros"),
        CONGO("Congo"),
        CONGO_DEMOCRATIC_REP("Congo (Democratic Rep)"),
        COSTA_RICA("Costa Rica"),
        CROATIA("Croatia"),
        CUBA("Cuba"),
        CURAÇAO("Curaçao"),
        CYPRUS("Cyprus"),
        CZECH_REPUBLIC("Czech Republic"),
        DENMARK("Denmark"),
        DJIBOUTI("Djibouti"),
        DOMINICA("Dominica"),
        DOMINICAN_REPUBLIC("Dominican Republic"),
        EAST_TIMOR("East Timor"),
        ECUADOR("Ecuador"),
        EGYPT("Egypt"),
        EL_SALVADOR("El Salvador"),
        EQUATORIAL_GUINEA("Equatorial Guinea"),
        ERITREA("Eritrea"),
        ESTONIA("Estonia"),
        ESWATINI("Eswatini"),
        ETHIOPIA("Ethiopia"),
        FIJI("Fiji"),
        FINLAND("Finland"),
        FRANCE("France"),
        GABON("Gabon"),
        GAMBIA("Gambia"),
        GEORGIA("Georgia"),
        GERMANY("Germany"),
        GHANA("Ghana"),
        GREECE("Greece"),
        GRENADA("Grenada"),
        GUATEMALA("Guatemala"),
        GUINEA("Guinea"),
        GUINEA_BISSAU("Guinea-Bissau"),
        GUYANA("Guyana"),
        HAITI("Haiti"),
        HONDURAS("Honduras"),
        HUNGARY("Hungary"),
        ICELAND("Iceland"),
        INDIA("India"),
        INDONESIA("Indonesia"),
        IRAN("Iran"),
        IRAQ("Iraq"),
        IRELAND_REPUBLIC("Ireland (Republic)"),
        ISRAEL("Israel"),
        ITALY("Italy"),
        IVORY_COAST("Ivory Coast"),
        JAMAICA("Jamaica"),
        JAPAN("Japan"),
        JORDAN("Jordan"),
        KAZAKHSTAN("Kazakhstan"),
        KENYA("Kenya"),
        KIRIBATI("Kiribati"),
        KOREA_NORTH("Korea North"),
        KOREA_SOUTH("Korea South"),
        KOSOVO("Kosovo"),
        KUWAIT("Kuwait"),
        KYRGYZSTAN("Kyrgyzstan"),
        LAOS("Laos"),
        LATVIA("Latvia"),
        LEBANON("Lebanon"),
        LESOTHO("Lesotho"),
        LIBERIA("Liberia"),
        LIBYA("Libya"),
        LIECHTENSTEIN("Liechtenstein"),
        LITHUANIA("Lithuania"),
        LUXEMBOURG("Luxembourg"),
        MACEDONIA("Macedonia"),
        MADAGASCAR("Madagascar"),
        MALAWI("Malawi"),
        MALAYSIA("Malaysia"),
        MALDIVES("Maldives"),
        MALI("Mali"),
        MALTA("Malta"),
        MARSHALL_ISLANDS("Marshall Islands"),
        MAURITANIA("Mauritania"),
        MAURITIUS("Mauritius"),
        MEXICO("Mexico"),
        MICRONESIA("Micronesia"),
        MOLDOVA("Moldova"),
        MONACO("Monaco"),
        MONGOLIA("Mongolia"),
        MONTENEGRO("Montenegro"),
        MOROCCO("Morocco"),
        MOZAMBIQUE("Mozambique"),
        MYANMAR("Myanmar"),
        NAMIBIA("Namibia"),
        NAURU("Nauru"),
        NEPAL("Nepal"),
        NETHERLANDS("Netherlands"),
        NEW_ZEALAND("New Zealand"),
        NICARAGUA("Nicaragua"),
        NIGER("Niger"),
        NIGERIA("Nigeria"),
        NORWAY("Norway"),
        OMAN("Oman"),
        PAKISTAN("Pakistan"),
        PALAU("Palau"),
        PALESTINE("Palestine"),
        PANAMA("Panama"),
        PAPUA_NEW_GUINEA("Papua New Guinea"),
        PARAGUAY("Paraguay"),
        PERU("Peru"),
        PHILIPPINES("Philippines"),
        POLAND("Poland"),
        PORTUGAL("Portugal"),
        QATAR("Qatar"),
        ROMANIA("Romania"),
        RUSSIAN_FEDERATION("Russian Federation"),
        RWANDA("Rwanda"),
        ST_KITTS_AND_NEVIS("St Kitts & Nevis"),
        ST_LUCIA("St Lucia"),
        SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent & the Grenadines"),
        SAMOA("Samoa"),
        SAN_MARINO("San Marino"),
        SAO_TOME_AND_PRINCIPE("Sao Tome & Principe"),
        SAUDI_ARABIA("Saudi Arabia"),
        SENEGAL("Senegal"),
        SERBIA("Serbia"),
        SEYCHELLES("Seychelles"),
        SIERRA_LEONE("Sierra Leone"),
        SINGAPORE("Singapore"),
        SLOVAKIA("Slovakia"),
        SLOVENIA("Slovenia"),
        SOLOMON_ISLANDS("Solomon Islands"),
        SOMALIA("Somalia"),
        SOUTH_AFRICA("South Africa"),
        SOUTH_SUDAN("South Sudan"),
        SPAIN("Spain"),
        SRI_LANKA("Sri Lanka"),
        SUDAN("Sudan"),
        SURINAME("Suriname"),
        SWEDEN("Sweden"),
        SWITZERLAND("Switzerland"),
        SYRIA("Syria"),
        TAIWAN("Taiwan"),
        TAJIKISTAN("Tajikistan"),
        TANZANIA("Tanzania"),
        THAILAND("Thailand"),
        TOGO("Togo"),
        TONGA("Tonga"),
        TRINIDAD_AND_TOBAGO("Trinidad & Tobago"),
        TUNISIA("Tunisia"),
        TURKEY("Turkey"),
        TURKMENISTAN("Turkmenistan"),
        TUVALU("Tuvalu"),
        UGANDA("Uganda"),
        UKRAINE("Ukraine"),
        UNITED_ARAB_EMIRATES("United Arab Emirates"),
        UNITED_KINGDOM("United Kingdom"),
        UNITED_STATES("United States"),
        URUGUAY("Uruguay"),
        UZBEKISTAN("Uzbekistan"),
        VANUATU("Vanuatu"),
        VATICAN_CITY("Vatican City"),
        VENEZUELA("Venezuela"),
        VIETNAM("Vietnam"),
        YEMEN("Yemen"),
        ZAMBIA("Zambia"),
        ZIMBABWE("Zimbabwe");

    private final String value;

    Country(String country) {
        value = country;
    }

    @Override
    public String toString() {
        return value;
    }
}
