server:
  port: 10001

  error:
    include-message: always
    include-exception: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update