version: 2
jobs:
  build_project:
    working_directory: ~/UserContact
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Run tests and check coverage
          command: ./gradlew check
      - store_artifacts:
          path: build/reports/junit/html
          destination: junit
      - store_artifacts:
          path: build/reports/jacoco
          destination: jacoco
      - run:
          name: Build jar
          command: ./gradlew build

workflows:
  version: 2
  default:
    jobs:
      - build_project
